// Generated by CoffeeScript 1.6.2
(function() {
  $(document).ready(function() {
    window.app = new App($('.that-iframe'));
    return app.login({
      username: 'some.user',
      password: 'some.pass'
    }, function(profile) {
      return console.log('Got user profile', profile);
    });
  });

}).call(this);
