// Generated by CoffeeScript 1.6.2
(function() {
  var App,
    __slice = [].slice;

  App = (function() {
    function App(frame_selector) {
      console.log('instantiation App with frame', $(frame_selector));
      this.iframe = $(frame_selector).get(0);
      window.addEventListener('message', $.proxy(this.handleFrameMessages, this));
    }

    App.prototype.handleFrameMessages = function(e) {
      var action, command, data;

      command = e.data.split(/:(.*)/);
      action = command[0];
      data = command[1] || "{}";
      data = JSON.parse(data);
      console.log('App received message', action, data);
      switch (action) {
        case 'loginComplete':
          return this.loginComplete(data);
      }
    };

    App.prototype.perform = function(action, data) {
      var _this = this;

      console.log('performing', action, 'with', data);
      return this.when_window_loads(function() {
        return _this.iframe.contentWindow.postMessage("" + action + ":" + (JSON.stringify(data)), 'http://localhost:5656/iframe.html');
      });
    };

    App.prototype.login = function(data, callback) {
      var _this = this;

      this.subscribe('login:complete', function(e, data) {
        _this.unsubscribe('login:complete', callback);
        return typeof callback === "function" ? callback(data) : void 0;
      });
      $.extend(data, {
        original_callback: 'loginComplete'
      });
      return this.perform('login', data);
    };

    App.prototype.loginComplete = function(data) {
      return this.publish('login:complete', data);
    };

    App.prototype.when_window_loads = function(callback) {
      if (document.readyState !== 'complete') {
        return window.onload = callback;
      } else {
        return typeof callback === "function" ? callback() : void 0;
      }
    };

    App.prototype.subscribe = function(event, callback) {
      console.debug('subscribing to', event);
      return $(this).on(event, callback);
    };

    App.prototype.unsubscribe = function(event, callback) {
      console.debug('dropping subscription to', event);
      return $(this).off(event, callback);
    };

    App.prototype.publish = function() {
      var data, event;

      event = arguments[0], data = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      console.log('publishing', event, 'with', data);
      return $(this).trigger(event, data);
    };

    return App;

  })();

  window.App = App;

}).call(this);
