// Generated by CoffeeScript 1.6.2
(function() {
  var App;

  App = (function() {
    function App(frame_selector) {
      console.log('instantiation App with frame', $(frame_selector));
      this.iframe = $(frame_selector).get(0);
      window.addEventListener('message', this.handleFrameMessages, false);
    }

    App.prototype.handleFrameMessages = function(e) {
      var action, command, data;

      command = e.data.split(/:(.*)/);
      action = command[0];
      data = JSON.parse(command[1]);
      console.log('App received message', action, data);
      switch (action) {
        case 'loginComlete':
          return this.loginComplete(data);
      }
    };

    App.prototype.perform = function(action, data) {
      var _this = this;

      console.log('performing', action, 'with', data);
      return this.when_window_loads(function() {
        return _this.iframe.contentWindow.postMessage("" + action + ":" + (JSON.stringify(data)), 'http://localhost:5656/iframe.html');
      });
    };

    App.prototype.login = function(data, callback) {
      return this.perform('login', data);
    };

    App.prototype.loginComplete = function(data) {
      return console.log('login complete...');
    };

    App.prototype.when_window_loads = function(callback) {
      if (document.readyState !== 'complete') {
        return window.onload = callback;
      } else {
        return typeof callback === "function" ? callback() : void 0;
      }
    };

    return App;

  })();

  window.App = App;

}).call(this);
