// Generated by CoffeeScript 1.6.2
(function() {
  var Frame;

  Frame = (function() {
    function Frame() {
      console.debug('Intantiating Frame');
    }

    Frame.prototype.handleClientMessages = function(e) {
      var action, command, data;

      command = e.data.split(/:(.*)/);
      action = command[0];
      data = JSON.parse(command[1]);
      console.log('Frame received message');
      console.debug('action:', action);
      console.debug('data:', data);
      switch (action) {
        case 'login':
          return console.log(this);
      }
    };

    Frame.prototype.login = function(data) {
      return console.log('should perform logging in with data', data);
    };

    return Frame;

  })();

  window.Frame = new Frame;

}).call(this);
